/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kumoasobi.scribble;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testBoardValidator() {
        
    }
}
