/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kumoasobi.scribble;

import javax.swing.SwingUtilities;

import com.kumoasobi.scribble.gui.GameWindow;

public class Main {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(GameWindow::new);
    }
}
